# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/LAB3_1_BlockDesign/LAB3_1_BlockDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB3_1_BlockDesign || ORIG_REF_NAME==LAB3_1_BlockDesign} -quiet] -quiet

# IP: bd/LAB3_1_BlockDesign/ip/LAB3_1_BlockDesign_processing_system7_0_0/LAB3_1_BlockDesign_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB3_1_BlockDesign_processing_system7_0_0 || ORIG_REF_NAME==LAB3_1_BlockDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/LAB3_1_BlockDesign/ip/LAB3_1_BlockDesign_axi_gpio_0_0/LAB3_1_BlockDesign_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB3_1_BlockDesign_axi_gpio_0_0 || ORIG_REF_NAME==LAB3_1_BlockDesign_axi_gpio_0_0} -quiet] -quiet

# IP: bd/LAB3_1_BlockDesign/ip/LAB3_1_BlockDesign_proc_sys_reset_0_0/LAB3_1_BlockDesign_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB3_1_BlockDesign_proc_sys_reset_0_0 || ORIG_REF_NAME==LAB3_1_BlockDesign_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/LAB3_1_BlockDesign/ip/LAB3_1_BlockDesign_xbar_0/LAB3_1_BlockDesign_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB3_1_BlockDesign_xbar_0 || ORIG_REF_NAME==LAB3_1_BlockDesign_xbar_0} -quiet] -quiet

# IP: bd/LAB3_1_BlockDesign/ip/LAB3_1_BlockDesign_axi_interconnect_0_0/LAB3_1_BlockDesign_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB3_1_BlockDesign_axi_interconnect_0_0 || ORIG_REF_NAME==LAB3_1_BlockDesign_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/LAB3_1_BlockDesign/ip/LAB3_1_BlockDesign_axi_gpio_0_1/LAB3_1_BlockDesign_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB3_1_BlockDesign_axi_gpio_0_1 || ORIG_REF_NAME==LAB3_1_BlockDesign_axi_gpio_0_1} -quiet] -quiet

# IP: bd/LAB3_1_BlockDesign/ip/LAB3_1_BlockDesign_auto_pc_0/LAB3_1_BlockDesign_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB3_1_BlockDesign_auto_pc_0 || ORIG_REF_NAME==LAB3_1_BlockDesign_auto_pc_0} -quiet] -quiet

# IP: bd/LAB3_1_BlockDesign/ip/LAB3_1_BlockDesign_axi_gpio_0_2/LAB3_1_BlockDesign_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB3_1_BlockDesign_axi_gpio_0_2 || ORIG_REF_NAME==LAB3_1_BlockDesign_axi_gpio_0_2} -quiet] -quiet

# XDC: e:/Academics/Sem 8/EE500_Digital_design_and_sysnthesis/Lab3/advanced-EmbdSysDesign-zynq/LAB_3/LAB_3.gen/sources_1/bd/LAB3_1_BlockDesign/LAB3_1_BlockDesign_ooc.xdc
