# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Academics/Sem 8/EE500_Digital_design_and_sysnthesis/Lab3/advanced-EmbdSysDesign-zynq/LAB_3/LAB_3.srcs/sources_1/bd/LAB3_1_BlockDesign/ip/LAB3_1_BlockDesign_auto_pc_0/LAB3_1_BlockDesign_auto_pc_0.xci
# IP: The module: 'LAB3_1_BlockDesign_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Academics/Sem 8/EE500_Digital_design_and_sysnthesis/Lab3/advanced-EmbdSysDesign-zynq/LAB_3/LAB_3.gen/sources_1/bd/LAB3_1_BlockDesign/ip/LAB3_1_BlockDesign_auto_pc_0/LAB3_1_BlockDesign_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LAB3_1_BlockDesign_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Academics/Sem 8/EE500_Digital_design_and_sysnthesis/Lab3/advanced-EmbdSysDesign-zynq/LAB_3/LAB_3.srcs/sources_1/bd/LAB3_1_BlockDesign/ip/LAB3_1_BlockDesign_auto_pc_0/LAB3_1_BlockDesign_auto_pc_0.xci
# IP: The module: 'LAB3_1_BlockDesign_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Academics/Sem 8/EE500_Digital_design_and_sysnthesis/Lab3/advanced-EmbdSysDesign-zynq/LAB_3/LAB_3.gen/sources_1/bd/LAB3_1_BlockDesign/ip/LAB3_1_BlockDesign_auto_pc_0/LAB3_1_BlockDesign_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LAB3_1_BlockDesign_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
